apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vault-credential-service
  namespace: vault-services
  labels:
    app: vault-credential-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vault-credential-service
