apiVersion: v1
kind: ConfigMap
metadata:
  name: sra-ecm-hashicorp-config
  namespace: default
data:
  VLT_BASE_URL: "http://192.168.23.167:8200/"
  VLT_SECRETS_ENGINE: "sra-ecm"
  VLT_USERNAME: "svc_sra_ecm"
  VLT_ECM_MAP: "/v1/sra_ecm/data/targets"
  SRASiteHostname: "pdasilvapra.beyondtrustcloud.com"
  SRAClientId: "7a5b8dcbd5a6b021036f34e9791d2fa6677643ad"
