apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm-example-plugin
  namespace: default
  labels:
    app: ecm-example-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecm-example-plugin
  template:
    metadata:
      labels:
        app: ecm-example-plugin
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ecm-plugin
          image: pdasilva1/ecm-k8s-plugin:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            # Vault Configuration
            - name: VLT_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: sra-ecm-hashicorp-config
                  key: VLT_BASE_URL
            - name: VLT_SECRETS_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: sra-ecm-hashicorp-config
                  key: VLT_SECRETS_ENGINE
            - name: VLT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: sra-ecm-hashicorp-config
                  key: VLT_USERNAME
            - name: VLT_ECM_MAP
              valueFrom:
                configMapKeyRef:
                  name: sra-ecm-hashicorp-config
                  key: VLT_ECM_MAP
            - name: VLT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sra-ecm-hashicorp-secret
                  key: VLT_PASSWORD
            # ECM Configuration
            - name: ECMConfig__SRASiteHostname
              valueFrom:
                configMapKeyRef:
                  name: sra-ecm-hashicorp-config
                  key: SRASiteHostname
            - name: ECMConfig__SRAClientId
              valueFrom:
                configMapKeyRef:
                  name: sra-ecm-hashicorp-config
                  key: SRAClientId
            - name: ECMConfig__SRAClientSecret
              valueFrom:
                secretKeyRef:
                  name: sra-ecm-hashicorp-secret
                  key: SRAClientSecret
      restartPolicy: Always
