apiVersion: v1
kind: Secret
metadata:
  name: sra-ecm-hashicorp-secret
  namespace: default
type: Opaque
stringData:
  VLT_PASSWORD: "P@ssw0rd123!"
  SRAClientSecret: "K4UlVFbQZBNIFnSJh/c4LVq76LyksENNfSubdxFS/9g="
