apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecm-plugin.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecm-plugin.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
