apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecm-plugin.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecm-plugin.labels" . | nindent 4 }}
type: Opaque
stringData:
  # HashiCorp Vault credentials
  vault-username: {{ .Values.secrets.vaultUsername | quote }}
  vault-password: {{ .Values.secrets.vaultPassword | quote }}
  # BeyondTrust PRA/SRA credentials
  sra-client-secret: {{ .Values.secrets.sraClientSecret | quote }}
