apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecm-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecm-plugin.labels" . | nindent 4 }}
  annotations:
    description: "Service for Vault Credential Injection API"
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ecm-plugin.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- end }}
